// Blog metadata accessors. The data itself comes from `virtual:blogs`, which is
// generated by vite-plugin-blogs from src/blogs/posts/*.mdx frontmatter — so the
// MDX files are the single source of truth (no hardcoded config).
import { BLOGS } from "virtual:blogs";
import type { BlogMeta } from "virtual:blogs";

export { BLOGS };
export type { BlogMeta };

export const getBlog = (slug: string): BlogMeta | undefined =>
  BLOGS.find((b) => b.slug === slug);

export const getBlogByGame = (gameKey: string): BlogMeta | undefined =>
  BLOGS.find((b) => b.gameKey === gameKey);

// Build the @vercel/og image URL for a post. Passed as query params so the edge
// function (api/og.tsx) stays self-contained, with no shared imports to bundle.
export function ogImageUrl(
  origin: string,
  blog: Pick<BlogMeta, "title" | "tag" | "accent">,
): string {
  const p = new URLSearchParams({
    title: blog.title,
    tag: blog.tag,
    accent: blog.accent,
  });
  return `${origin}/api/og?${p.toString()}`;
}
